//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWS_Lite.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWS_Lite.lang.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Windows Store Apps entfernen.
        /// </summary>
        internal static string btnDeleteAllWindows10Apps {
            get {
                return ResourceManager.GetString("btnDeleteAllWindows10Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft OneDrive entfernen.
        /// </summary>
        internal static string btnDeleteOneDrive {
            get {
                return ResourceManager.GetString("btnDeleteOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löse Bildschirmdrehung.
        /// </summary>
        internal static string btnFixRotateScreen {
            get {
                return ResourceManager.GetString("btnFixRotateScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die HOSTS-Datei bearbeiten.
        /// </summary>
        internal static string btnOpenAndEditHosts {
            get {
                return ResourceManager.GetString("btnOpenAndEditHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experten-Modus aktivieren.
        /// </summary>
        internal static string btnProfessionalMode {
            get {
                return ResourceManager.GetString("btnProfessionalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System wiederherstellen.
        /// </summary>
        internal static string btnRestoreSystem {
            get {
                return ResourceManager.GetString("btnRestoreSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch Internetseiten, die spionieren, blockieren..
        /// </summary>
        internal static string checkBoxAddToHosts {
            get {
                return ResourceManager.GetString("checkBoxAddToHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemwiederherstellungspunkt erstellen.
        /// </summary>
        internal static string checkBoxCreateSystemRestorePoint {
            get {
                return ResourceManager.GetString("checkBoxCreateSystemRestorePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Windows Store Apps entfernen.
        /// </summary>
        internal static string checkBoxDeleteWindows10Apps {
            get {
                return ResourceManager.GetString("checkBoxDeleteWindows10Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzeinstellungen deaktivieren.
        /// </summary>
        internal static string checkBoxDisablePrivateSettings {
            get {
                return ResourceManager.GetString("checkBoxDisablePrivateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Defender (Antivirus) deaktivieren.
        /// </summary>
        internal static string checkBoxDisableWindowsDefender {
            get {
                return ResourceManager.GetString("checkBoxDisableWindowsDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tastaturprotokolle und Benutzerprotokolle löschen.
        /// </summary>
        internal static string checkBoxKeyLoggerAndTelemetry {
            get {
                return ResourceManager.GetString("checkBoxKeyLoggerAndTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Bilderanzeige festlegen.
        /// </summary>
        internal static string checkBoxSetDefaultPhoto {
            get {
                return ResourceManager.GetString("checkBoxSetDefaultPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spionageaufträge beenden.
        /// </summary>
        internal static string checkBoxSPYTasks {
            get {
                return ResourceManager.GetString("checkBoxSPYTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles erfolgreich erledigt!
        ///
        ///Allerdings muss das System neu gestartet werden.
        ///Wollen Sie jetzt neu starten?.
        /// </summary>
        internal static string CompleteMSG {
            get {
                return ResourceManager.GetString("CompleteMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps löschen.
        /// </summary>
        internal static string DeleteApps {
            get {
                return ResourceManager.GetString("DeleteApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivieren.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivieren.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgang abgeschlossen. Leider ist ein Fehler dabei eingetreten: {0}
        ///
        ///Es ist ein Neustart notwendig. 
        ///Jetzt neu starten?.
        /// </summary>
        internal static string ErrorMSG {
            get {
                return ResourceManager.GetString("ErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Store Apps werden gelöscht. Diese Aktion ist nicht umkehrbar..
        /// </summary>
        internal static string labelInfoDeleteMetroApps {
            get {
                return ResourceManager.GetString("labelInfoDeleteMetroApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verweise.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drücken Sie OK und warten Sie ungefähr 15 Minuten..
        /// </summary>
        internal static string PressOkAndWait15 {
            get {
                return ResourceManager.GetString("PressOkAndWait15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragen.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guten Tag. Willkommen bei &quot;Destroy Windows 10 Spying&quot;.
        ///Dieses Programm ist Quelloffen und dient dem Schutz ihrer Privatsphäre. 
        ///
        ///Es verhindert, das Windows 10 Daten über Sie und ihre Tätigkeiten erfasst. Weiterhin verhindert es auch zukünftige Programme, die versuchen Ihre Benutzerdaten zu sammeln.
        ///
        ///Ferner kann die Anwendung, sofern Sie es wünschen, auch die Windows Store Anwendungen entfernen. Diese laufen oftmals im Hintergrund und verwenden so den Speicher und die Rechenleistung ihrer Computers.
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadMeTextBox {
            get {
                return ResourceManager.GetString("ReadMeTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sie sicher?.
        /// </summary>
        internal static string Really {
            get {
                return ResourceManager.GetString("Really", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alte Firewall-Regeln von uns entfernen..
        /// </summary>
        internal static string RemoveAllOldFirewallRules {
            get {
                return ResourceManager.GetString("RemoveAllOldFirewallRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einen Fehler melden..
        /// </summary>
        internal static string ReportABug {
            get {
                return ResourceManager.GetString("ReportABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Neustart notwendig. Soll jetzt neu gestartet werden?.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        internal static string tabPageAbout {
            get {
                return ResourceManager.GetString("tabPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string tabPageMain {
            get {
                return ResourceManager.GetString("tabPageMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anleitung.
        /// </summary>
        internal static string tabPageReadMe {
            get {
                return ResourceManager.GetString("tabPageReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string tabPageSettings {
            get {
                return ResourceManager.GetString("tabPageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkzeug.
        /// </summary>
        internal static string tabPageUtilites {
            get {
                return ResourceManager.GetString("tabPageUtilites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
