//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace DWS_Lite.lang {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class fr_FR {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("DWS_Lite.lang.fr-FR", typeof(fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer toutes les applications Metro de Windows 10.
        /// </summary>
        internal static string btnDeleteAllWindows10Apps {
            get {
                return ResourceManager.GetString("btnDeleteAllWindows10Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer OneDrive.
        /// </summary>
        internal static string btnDeleteOneDrive {
            get {
                return ResourceManager.GetString("btnDeleteOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir et Modifier le fichier HOSTS.
        /// </summary>
        internal static string btnOpenAndEditHosts {
            get {
                return ResourceManager.GetString("btnOpenAndEditHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer le Mode Professionnel.
        /// </summary>
        internal static string btnProfessionalMode {
            get {
                return ResourceManager.GetString("btnProfessionalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurer le Système.
        /// </summary>
        internal static string btnRestoreSystem {
            get {
                return ResourceManager.GetString("btnRestoreSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter des domaines espion au fichier HOSTS et bloquer dans le pare-feu Windows.
        /// </summary>
        internal static string checkBoxAddToHosts {
            get {
                return ResourceManager.GetString("checkBoxAddToHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un point de restauration système.
        /// </summary>
        internal static string checkBoxCreateSystemRestorePoint {
            get {
                return ResourceManager.GetString("checkBoxCreateSystemRestorePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer les applications Métro de Windows 10.
        /// </summary>
        internal static string checkBoxDeleteWindows10Apps {
            get {
                return ResourceManager.GetString("checkBoxDeleteWindows10Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver les paramètres privés.
        /// </summary>
        internal static string checkBoxDisablePrivateSettings {
            get {
                return ResourceManager.GetString("checkBoxDisablePrivateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver Windows Defender.
        /// </summary>
        internal static string checkBoxDisableWindowsDefender {
            get {
                return ResourceManager.GetString("checkBoxDisableWindowsDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer le KeyLogger et la Télémétrie.
        /// </summary>
        internal static string checkBoxKeyLoggerAndTelemetry {
            get {
                return ResourceManager.GetString("checkBoxKeyLoggerAndTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visionneuse de photos Windows par défaut.
        /// </summary>
        internal static string checkBoxSetDefaultPhoto {
            get {
                return ResourceManager.GetString("checkBoxSetDefaultPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver les tâches de l&apos;Espion.
        /// </summary>
        internal static string checkBoxSPYTasks {
            get {
                return ResourceManager.GetString("checkBoxSPYTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fini!
        ///Un redémarrage est nécessaire pour désactiver tous les logiciels espions.
        ///Redémarrer maintenant ?.
        /// </summary>
        internal static string CompleteMSG {
            get {
                return ResourceManager.GetString("CompleteMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer les applications.
        /// </summary>
        internal static string DeleteApps {
            get {
                return ResourceManager.GetString("DeleteApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détruire les Espions de Windows 10.
        /// </summary>
        internal static string DestroyWindowsSpying {
            get {
                return ResourceManager.GetString("DestroyWindowsSpying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fini avec des erreurs - {0}
        ///Un redémarrage est nécessaire pour désactiver tous les logiciels espions.
        ///Redémarrer maintenant?.
        /// </summary>
        internal static string ErrorMSG {
            get {
                return ResourceManager.GetString("ErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les applications METRO sont définitivement supprimés, sans possibilité de récupération..
        /// </summary>
        internal static string labelInfoDeleteMetroApps {
            get {
                return ResourceManager.GetString("labelInfoDeleteMetroApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liens.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez sur OK et attendez 15 minutes..
        /// </summary>
        internal static string PressOkAndWait15 {
            get {
                return ResourceManager.GetString("PressOkAndWait15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program destroys spying on Windows 7/8/8.1/10.
        ///The program is open source code, which is on github.
        ///This program completely destroys spying. Removes some elements of telemetry and the other turns off, disables Windows Defender, Cortana, and much more. As the program disables Windows Update, which allows you to remain anonymous and not to receive updates of new spyware.
        ///The delete Metro applications is very good, because they work in the background, and devour memory, and some of them spying on you.        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadMeTextBox {
            get {
                return ResourceManager.GetString("ReadMeTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vraiment ?.
        /// </summary>
        internal static string Really {
            get {
                return ResourceManager.GetString("Really", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all old DWS firewall rules.
        /// </summary>
        internal static string RemoveAllOldFirewallRules {
            get {
                return ResourceManager.GetString("RemoveAllOldFirewallRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        internal static string ReportABug {
            get {
                return ResourceManager.GetString("ReportABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nécessite un redémarrage.
        ///Redémarrer maintenant ?.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce programme ne fonctionne que sur Windows 10.
        /// </summary>
        internal static string RunOnlyWin10 {
            get {
                return ResourceManager.GetString("RunOnlyWin10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos.
        /// </summary>
        internal static string tabPageAbout {
            get {
                return ResourceManager.GetString("tabPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        internal static string tabPageMain {
            get {
                return ResourceManager.GetString("tabPageMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisez Moi.
        /// </summary>
        internal static string tabPageReadMe {
            get {
                return ResourceManager.GetString("tabPageReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string tabPageSettings {
            get {
                return ResourceManager.GetString("tabPageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilitaires.
        /// </summary>
        internal static string tabPageUtilites {
            get {
                return ResourceManager.GetString("tabPageUtilites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
