//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWS_Lite.lang {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class it_IT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal it_IT() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWS_Lite.lang.it-IT", typeof(it_IT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disinstalla tutte le App Metro di Windows 10.
        /// </summary>
        internal static string btnDeleteAllWindows10Apps {
            get {
                return ResourceManager.GetString("btnDeleteAllWindows10Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disinstalla One Drive.
        /// </summary>
        internal static string btnDeleteOneDrive {
            get {
                return ResourceManager.GetString("btnDeleteOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apri e modifica file hosts.
        /// </summary>
        internal static string btnOpenAndEditHosts {
            get {
                return ResourceManager.GetString("btnOpenAndEditHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abilità la modalità Proffesionale.
        /// </summary>
        internal static string btnProfessionalMode {
            get {
                return ResourceManager.GetString("btnProfessionalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ripristino del Sistema.
        /// </summary>
        internal static string btnRestoreSystem {
            get {
                return ResourceManager.GetString("btnRestoreSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiungi i domini spia in hosts e Firewall.
        /// </summary>
        internal static string checkBoxAddToHosts {
            get {
                return ResourceManager.GetString("checkBoxAddToHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crea un punto di ripristino.
        /// </summary>
        internal static string checkBoxCreateSystemRestorePoint {
            get {
                return ResourceManager.GetString("checkBoxCreateSystemRestorePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disinstalla App Metro di Windows 10.
        /// </summary>
        internal static string checkBoxDeleteWindows10Apps {
            get {
                return ResourceManager.GetString("checkBoxDeleteWindows10Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disabilita le impostazioni private.
        /// </summary>
        internal static string checkBoxDisablePrivateSettings {
            get {
                return ResourceManager.GetString("checkBoxDisablePrivateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disabilita Windows Defender.
        /// </summary>
        internal static string checkBoxDisableWindowsDefender {
            get {
                return ResourceManager.GetString("checkBoxDisableWindowsDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disabilita KeyLogger e telemetria.
        /// </summary>
        internal static string checkBoxKeyLoggerAndTelemetry {
            get {
                return ResourceManager.GetString("checkBoxKeyLoggerAndTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ripristina Visualizzatore di foto.
        /// </summary>
        internal static string checkBoxSetDefaultPhoto {
            get {
                return ResourceManager.GetString("checkBoxSetDefaultPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disabilità processi spia.
        /// </summary>
        internal static string checkBoxSPYTasks {
            get {
                return ResourceManager.GetString("checkBoxSPYTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Completato.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Completato.
        ///E&apos; necessario riavviare il PC.
        ///Riavviare ora?.
        /// </summary>
        internal static string CompleteMSG {
            get {
                return ResourceManager.GetString("CompleteMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancella.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disinstalla le App.
        /// </summary>
        internal static string DeleteApps {
            get {
                return ResourceManager.GetString("DeleteApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disabilita.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abilita.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Oh qualcosa è andato storto. Errore - {0}
        ///E&apos; necessario comunque riavviare il PC.
        ///Riavviare ora?.
        /// </summary>
        internal static string ErrorMSG {
            get {
                return ResourceManager.GetString("ErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Specifica la posizione del file msosync.exe. Se Office 2016 è installato nella directory di default, Disco locale C, clicca &quot;Cancella&quot;.
        /// </summary>
        internal static string FindOffice16FileT {
            get {
                return ResourceManager.GetString("FindOffice16FileT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazione.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alcune App Metro vengono disinstallate in modo permanente.
        /// </summary>
        internal static string labelInfoDeleteMetroApps {
            get {
                return ResourceManager.GetString("labelInfoDeleteMetroApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Collegamenti.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clicca Ok ed aspetta 15 minuti..
        /// </summary>
        internal static string PressOkAndWait15 {
            get {
                return ResourceManager.GetString("PressOkAndWait15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Domanda.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Questo software elimina lo spionaggio in Windows 7/8/8.1/10,  è un open-source ed è visionabile su GitHub.
        ///Questo programma elimina completamente lo spionaggio. Rimuove alcuni elementi della telemetria e ne disattiva altri, inoltre disabilita Windows Defender, Cortana, e molto altro. Inoltre  disabilita Windows Update, consentendo di mantenere l&apos;anonimato e di non ricevere nuovi aggiornamenti spyware.
        ///La disinstallazione delle applicazioni Metro è un bene, perché lavorano in background, consumano molta me [stringa troncata]&quot;;.
        /// </summary>
        internal static string ReadMeTextBox {
            get {
                return ResourceManager.GetString("ReadMeTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sicuro?.
        /// </summary>
        internal static string Really {
            get {
                return ResourceManager.GetString("Really", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rimuovi le vecchie impostazioni del Firewall.
        /// </summary>
        internal static string RemoveAllOldFirewallRules {
            get {
                return ResourceManager.GetString("RemoveAllOldFirewallRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riporta un bug.
        /// </summary>
        internal static string ReportABug {
            get {
                return ResourceManager.GetString("ReportABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; necessario riavviare il sistema
        ///Riavviare ora?.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni.
        /// </summary>
        internal static string tabPageAbout {
            get {
                return ResourceManager.GetString("tabPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pagina principale.
        /// </summary>
        internal static string tabPageMain {
            get {
                return ResourceManager.GetString("tabPageMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Leggimi.
        /// </summary>
        internal static string tabPageReadMe {
            get {
                return ResourceManager.GetString("tabPageReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni.
        /// </summary>
        internal static string tabPageSettings {
            get {
                return ResourceManager.GetString("tabPageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pagine utili.
        /// </summary>
        internal static string tabPageUtilites {
            get {
                return ResourceManager.GetString("tabPageUtilites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attenzione.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
