//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWS_Lite.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWS_Lite.lang.pt-BR", typeof(pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar todos os apps Metro do Windows 10.
        /// </summary>
        internal static string btnDeleteAllWindows10Apps {
            get {
                return ResourceManager.GetString("btnDeleteAllWindows10Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar One Drive.
        /// </summary>
        internal static string btnDeleteOneDrive {
            get {
                return ResourceManager.GetString("btnDeleteOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir e editar o arquivo HOSTS.
        /// </summary>
        internal static string btnOpenAndEditHosts {
            get {
                return ResourceManager.GetString("btnOpenAndEditHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar modo profissional.
        /// </summary>
        internal static string btnProfessionalMode {
            get {
                return ResourceManager.GetString("btnProfessionalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar sistema.
        /// </summary>
        internal static string btnRestoreSystem {
            get {
                return ResourceManager.GetString("btnRestoreSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar domínios de espionagem no arquivo hosts e bloquear no Firewall do Windows.
        /// </summary>
        internal static string checkBoxAddToHosts {
            get {
                return ResourceManager.GetString("checkBoxAddToHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar ponto de restauração.
        /// </summary>
        internal static string checkBoxCreateSystemRestorePoint {
            get {
                return ResourceManager.GetString("checkBoxCreateSystemRestorePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Apps Metro do Windows 10.
        /// </summary>
        internal static string checkBoxDeleteWindows10Apps {
            get {
                return ResourceManager.GetString("checkBoxDeleteWindows10Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitar configuracões privadas.
        /// </summary>
        internal static string checkBoxDisablePrivateSettings {
            get {
                return ResourceManager.GetString("checkBoxDisablePrivateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitar Windows Defender.
        /// </summary>
        internal static string checkBoxDisableWindowsDefender {
            get {
                return ResourceManager.GetString("checkBoxDisableWindowsDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Keylogger e Telemetría.
        /// </summary>
        internal static string checkBoxKeyLoggerAndTelemetry {
            get {
                return ResourceManager.GetString("checkBoxKeyLoggerAndTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir visualizador de fotos padrão do Windows .
        /// </summary>
        internal static string checkBoxSetDefaultPhoto {
            get {
                return ResourceManager.GetString("checkBoxSetDefaultPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitar tareas de espionagem.
        /// </summary>
        internal static string checkBoxSPYTasks {
            get {
                return ResourceManager.GetString("checkBoxSPYTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído.
        /// </summary>
        internal static string Compele {
            get {
                return ResourceManager.GetString("Compele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído!
        ///Uma reinicialização é necessária para desativar todos os spywares.
        ///Reiniciar agora?.
        /// </summary>
        internal static string CompleteMSG {
            get {
                return ResourceManager.GetString("CompleteMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar apps.
        /// </summary>
        internal static string DeleteApps {
            get {
                return ResourceManager.GetString("DeleteApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitar.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizado. Erros - {0}
        ///Uma reinicialização é necessária para desativar todos os spywares.
        ///Reiniciar agora?.
        /// </summary>
        internal static string ErrorMSG {
            get {
                return ResourceManager.GetString("ErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the path to the file msosync.exe. If Office 2016 is installed as standard on the drive C, press &quot;Cancel&quot;.
        /// </summary>
        internal static string FindOffice16FileT {
            get {
                return ResourceManager.GetString("FindOffice16FileT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os aplicativos METRO são apagados permanentemente, sem a possibilidade de recuperação..
        /// </summary>
        internal static string labelInfoDeleteMetroApps {
            get {
                return ResourceManager.GetString("labelInfoDeleteMetroApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presione OK, e aguarde 15 minutos..
        /// </summary>
        internal static string PressOkAndWait15 {
            get {
                return ResourceManager.GetString("PressOkAndWait15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program destroys spying on Windows 7/8/8.1/10.
        ///The program is open source code, which is on github.
        ///This program completely destroys spying. Removes some elements of telemetry and the other turns off, disables Windows Defender, Cortana, and much more. As the program disables Windows Update, which allows you to remain anonymous and not to receive updates of new spyware.
        ///The delete Metro applications is very good, because they work in the background, and devour memory, and some of them spying on you.
        ///Als [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadMeTextBox {
            get {
                return ResourceManager.GetString("ReadMeTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza?.
        /// </summary>
        internal static string Really {
            get {
                return ResourceManager.GetString("Really", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover todas as regras antigas de firewall do DWS.
        /// </summary>
        internal static string RemoveAllOldFirewallRules {
            get {
                return ResourceManager.GetString("RemoveAllOldFirewallRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informar um erro.
        /// </summary>
        internal static string ReportABug {
            get {
                return ResourceManager.GetString("ReportABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário reiniciar.
        ///Reiniciar agora?.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string tabPageAbout {
            get {
                return ResourceManager.GetString("tabPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        internal static string tabPageMain {
            get {
                return ResourceManager.GetString("tabPageMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leia-me.
        /// </summary>
        internal static string tabPageReadMe {
            get {
                return ResourceManager.GetString("tabPageReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string tabPageSettings {
            get {
                return ResourceManager.GetString("tabPageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilidades.
        /// </summary>
        internal static string tabPageUtilites {
            get {
                return ResourceManager.GetString("tabPageUtilites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuidado.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
